#!/usr/bin/env python3
"""
Interactive wizard to create .env for RadioPlayerV3.
Supports generating SESSION_STRING via Pyrogram (phone login) or pasting an existing string.
Run from the project root after: pip install -r requirements.txt
"""

from __future__ import annotations

import os
import shutil
import sys


def _prompt(label: str, default: str | None = None, required: bool = True) -> str:
    hint = f" [{default}]" if default is not None and default != "" else ""
    while True:
        raw = input(f"{label}{hint}: ").strip()
        if raw:
            return raw
        if default is not None:
            return default
        if not required:
            return ""
        print("  (This value is required.)")


def _prompt_int(label: str, default: int | None = None, required: bool = True) -> int | None:
    hint = f" [{default}]" if default is not None else ""
    while True:
        raw = input(f"{label}{hint}: ").strip()
        if not raw:
            if default is not None:
                return default
            if not required:
                return None
            print("  (This value is required.)")
            continue
        try:
            return int(raw)
        except ValueError:
            print("  (Enter a whole number, e.g. -1001234567890 for a supergroup.)")


def _env_quote(value: str) -> str:
    if value is None:
        return '""'
    s = str(value)
    if not s:
        return '""'
    if any(c in s for c in '\n\r"\\') or " " in s or s.startswith("#"):
        escaped = s.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return s


def _write_env(path: str, data: dict[str, str], *, generated_by: str = "setup_env.py") -> None:
    lines = [
        f"# RadioPlayerV3 — generated by {generated_by}",
        "# https://my.telegram.org/apps — API_ID / API_HASH",
        "",
    ]
    order = [
        "API_ID",
        "API_HASH",
        "BOT_TOKEN",
        "SESSION_STRING",
        "CHAT_ID",
        "AUTH_USERS",
        "STREAM_URL",
        "LOG_GROUP",
        "REPLY_MESSAGE",
        "ADMIN_ONLY",
        "MAXIMUM_DURATION",
        "DELAY",
        "EDIT_TITLE",
        "RADIO_TITLE",
        "HEROKU_API_KEY",
        "HEROKU_APP_NAME",
    ]
    for key in order:
        if key in data:
            lines.append(f'{key}={_env_quote(data[key])}')
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")


def _generate_session_string(api_id: int, api_hash: str) -> str:
    try:
        from pyrogram import Client
    except ImportError as e:
        print(
            "Pyrogram is not installed. Install dependencies first:\n"
            "  pip install -r requirements.txt"
        )
        raise SystemExit(1) from e

    session_name = "radio_setup_wizard"
    session_files = [f"{session_name}.session", f"{session_name}.session-journal"]

    print()
    print("— Pyrogram will ask for your phone number and the login code from Telegram.")
    print("— Use the same Telegram account that is (or will be) admin in the voice chat.")
    print()

    app = Client(session_name, api_id=api_id, api_hash=api_hash)
    try:
        app.start()
        session_string = app.export_session_string()
    finally:
        app.stop()
        for p in session_files:
            if os.path.isfile(p):
                try:
                    os.remove(p)
                except OSError:
                    pass

    return session_string


def project_root() -> str:
    return os.path.dirname(os.path.abspath(__file__))


def interactive_collect() -> dict[str, str]:
    """Same questions as the .env wizard; returns key → value strings for _write_env."""
    print()
    print("Required values")
    print("---------------")
    api_id = _prompt_int("API_ID (from https://my.telegram.org/apps)")
    api_hash = _prompt("API_HASH")
    bot_token = _prompt("BOT_TOKEN (from @BotFather)")
    chat_id = _prompt(
        "CHAT_ID (e.g. -1001234567890) or public @username of the group/channel without @"
    )
    auth_users = _prompt(
        "AUTH_USERS (Telegram user IDs allowed to use admin commands, space-separated)"
    )

    print()
    print("SESSION_STRING (Pyrogram user account — needed for the userbot side)")
    print("  [1] Generate now (phone login in this terminal)")
    print("  [2] Paste an existing session string")
    choice = _prompt("Choose 1 or 2", default="1").strip()
    if choice not in ("1", "2"):
        print("  (Using option 1: generate session.)")
        choice = "1"

    session_string = ""
    if choice == "2":
        session_string = _prompt("Paste SESSION_STRING")
    else:
        session_string = _generate_session_string(api_id, api_hash)
        print()
        print("Generated SESSION_STRING (also saved into .env).")
        print("(Keep it secret — it grants access to your Telegram account.)")
        print()

    print()
    print("Optional values (Enter = use default)")
    print("-----------------------------------")
    stream_default = "http://peridot.streamguys.com:7150/Mirchi"
    stream_url = _prompt("STREAM_URL (radio stream or YouTube URL)", default=stream_default)

    log_raw = _prompt(
        "LOG_GROUP (chat ID for playlist logs; leave empty if not needed)",
        default="",
        required=False,
    )

    reply_raw = _prompt(
        "REPLY_MESSAGE (auto-reply when someone PMs the user account; empty = disable userbot plugins folder)",
        default="",
        required=False,
    )

    admin_only = _prompt("ADMIN_ONLY (True/False)", default="False")
    max_dur = _prompt("MAXIMUM_DURATION (minutes for /play)", default="15")
    delay = _prompt("DELAY (seconds)", default="10")
    edit_title = _prompt("EDIT_TITLE (True/False)", default="True")
    radio_title = _prompt("RADIO_TITLE (voice chat title; or 'False' to disable)", default="RADIO 24/7 | LIVE")

    print()
    print("Heroku (optional — only if you use Heroku integration in the bot)")
    print("----------------------------------------------------------------")
    heroku_key = _prompt("HEROKU_API_KEY (empty to skip)", default="", required=False)
    heroku_app = _prompt("HEROKU_APP_NAME (empty to skip)", default="", required=False)

    data: dict[str, str] = {
        "API_ID": str(api_id),
        "API_HASH": api_hash,
        "BOT_TOKEN": bot_token,
        "SESSION_STRING": session_string,
        "CHAT_ID": str(chat_id),
        "AUTH_USERS": auth_users,
        "STREAM_URL": stream_url,
        "ADMIN_ONLY": admin_only,
        "MAXIMUM_DURATION": max_dur,
        "DELAY": delay,
        "EDIT_TITLE": edit_title,
        "RADIO_TITLE": radio_title,
    }
    if log_raw:
        data["LOG_GROUP"] = log_raw
    if reply_raw:
        data["REPLY_MESSAGE"] = reply_raw
    if heroku_key:
        data["HEROKU_API_KEY"] = heroku_key
    if heroku_app:
        data["HEROKU_APP_NAME"] = heroku_app

    return data


def main() -> None:
    root = project_root()
    env_path = os.path.join(root, ".env")

    print()
    print("RadioPlayerV3 — .env setup")
    print("-" * 40)
    print()

    if os.path.isfile(env_path):
        bak = env_path + ".bak"
        try:
            shutil.copy2(env_path, bak)
            print(f"Existing .env copied to {os.path.basename(bak)}")
        except OSError as e:
            print(f"Warning: could not backup .env: {e}")
        print()

    data = interactive_collect()
    _write_env(env_path, data)
    print()
    print(f"Wrote {env_path}")
    print("Start the bot: run.bat   or   py -3.10 main.py")
    print("(On Windows, Python 3.12 cannot install tgcalls; use 3.10 or 3.11.)")
    print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nAborted.")
        sys.exit(130)
